#!/usr/bin/env python3
"""Keep README.md's "Current corpus" block in step with the corpus.

    python scripts/check_docs.py --write   # regenerate the block
    python scripts/check_docs.py --check   # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import re
import sys

from corpus import REPO_ROOT, load_records
from corpus_report import summarize

README = REPO_ROOT / "README.md"
BEGIN = "<!-- BEGIN GENERATED CORPUS STATS -->"
END = "<!-- END GENERATED CORPUS STATS -->"


def render_block() -> str:
    s = summarize(load_records())
    lines = [
        BEGIN,
        "<!-- Generated by scripts/check_docs.py; do not edit this block by hand. -->",
        f"**{s['total']} structure records** are currently committed.",
        "",
        "| Category | Records | | Status | Records |",
        "|---|---:|---|---|---:|",
    ]
    cats = list(s["by_category"].items())
    stats = list(s["by_status"].items())
    for i in range(max(len(cats), len(stats))):
        c = cats[i] if i < len(cats) else ("", "")
        t = stats[i] if i < len(stats) else ("", "")
        lines.append(f"| {c[0]} | {c[1]} | | {t[0]} | {t[1]} |")
    lines += [
        "",
        f"{s['go_grounded']} records are grounded in GO; {s['minted']} carry minted identifiers. "
        f"{s['with_components']} list components, {s['with_graphs']} carry causal graphs "
        f"({s['edges']} evidence-backed edges), and {s['with_traits']} link to TraitMech traits.",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pattern.search(text):
        print(f"README.md has no {BEGIN} ... {END} block", file=sys.stderr)
        return 1
    new_text = pattern.sub(lambda _m: render_block(), text)
    if args.write:
        README.write_text(new_text, encoding="utf-8")
        print("README.md corpus block refreshed")
        return 0
    if new_text != text:
        print("README.md corpus block is stale; run `just docs-stats`", file=sys.stderr)
        return 1
    print("README.md corpus block is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
